<#
.SYNOPSIS
    Registers a Windows Scheduled Task that runs the whale-tracker Observer
    every N minutes. NOT run automatically -- Ahmet runs this manually after
    reviewing it, per Brain-Eleven's "don't silently create standing
    background automation" practice.

.DESCRIPTION
    Creates a task that runs, from this project's own directory:
        uv run python -m whale_tracker.observe --min-usd 1000000 --log-file data\observer.log
    Output goes to data\observer.log (timestamped, appended) since a
    scheduled task's stdout is otherwise discarded.

    The task's action launches a generated VBScript wrapper
    (scripts\run-observer-hidden.vbs) via wscript.exe instead of calling
    uv.exe directly. Task Scheduler shows a visible console window for a
    console-subsystem executable launched directly, even with
    -WindowStyle Hidden on a wrapping powershell.exe (that only hides the
    PowerShell host's own window, not reliably its child's) -- confirmed
    the hard way: this is what was flashing a console every 15 minutes.
    WScript.Shell.Run(..., 0, True) is the standard, reliable Windows
    mechanism for genuinely windowless execution regardless of session
    type; the VBS is regenerated (not hand-maintained) each time this
    script runs, since it embeds this machine's resolved uv.exe path and
    project root.

.PARAMETER IntervalMinutes
    How often to run. Default 15 -- frequent enough to catch real activity,
    infrequent enough not to hammer the free public RPC/APIs this project
    relies on (see docs/DATA-SOURCES.md and docs/TECHNICAL-APPROACH.md for
    why these are rate-sensitive).

.EXAMPLE
    .\scripts\register-task.ps1
    .\scripts\register-task.ps1 -IntervalMinutes 30

.NOTES
    To remove the task later:
        Unregister-ScheduledTask -TaskName "whale-tracker-observer" -Confirm:$false
    To see its recent run history:
        Get-ScheduledTaskInfo -TaskName "whale-tracker-observer"
#>

param(
    [int]$IntervalMinutes = 15
)

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$UvPath = (Get-Command uv -ErrorAction Stop).Source
$VbsPath = Join-Path $PSScriptRoot "run-observer-hidden.vbs"

$VbsCommand = "`"$UvPath`" run python -m whale_tracker.observe --min-usd 1000000 --log-file data\observer.log"
$VbsContent = @"
' Auto-generated by register-task.ps1 -- do not hand-edit, it will be
' overwritten. Runs the observer with a genuinely hidden window (the
' 3rd argument to .Run, True, means "wait for it to finish" so the
' scheduled task's own run duration reflects the real one).
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "$ProjectRoot"
WshShell.Run "$($VbsCommand.Replace('"', '""'))", 0, True
"@
Set-Content -Path $VbsPath -Value $VbsContent -Encoding ASCII

$Action = New-ScheduledTaskAction `
    -Execute "wscript.exe" `
    -Argument "`"$VbsPath`"" `
    -WorkingDirectory $ProjectRoot

# TimeSpan]::MaxValue is out of range for a scheduled task's XML duration
# field (confirmed empirically -- Register-ScheduledTask rejects it with
# "Duration:P99999999DT23H59M59S"). 10 years is effectively indefinite for
# this project and is a value Task Scheduler actually accepts.
$Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes) `
    -RepetitionDuration (New-TimeSpan -Days 3650)

$Settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5) `
    -DontStopOnIdleEnd `
    -StartWhenAvailable

Register-ScheduledTask `
    -TaskName "whale-tracker-observer" `
    -Action $Action `
    -Trigger $Trigger `
    -Settings $Settings `
    -Description "whale-tracker Gozlemci -- her $IntervalMinutes dakikada bir veri toplar, islem yapmaz. Gizli calisir (scripts\run-observer-hidden.vbs uzerinden)." `
    -Force `
    -ErrorAction Stop

Write-Host "Task registered: whale-tracker-observer (every $IntervalMinutes min, hidden window)"
Write-Host "Log file: $ProjectRoot\data\observer.log"
Write-Host "To remove: Unregister-ScheduledTask -TaskName 'whale-tracker-observer' -Confirm:`$false"
